apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: registry-hn02.fke.fptcloud.com/7cdebed7-3ddd-4b99-b9a3-831496d04540/votingapp_vote:latest
        imagePullPolicy: IfNotPresent
        name: vote
        ports:
        - containerPort: 80
          name: http
        resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
